import { describe, expect, it } from "vitest";

import { parseGeneratedSubscriptionUrl } from "../src/app/lib/generated-subscription";

function tokenFor(value: unknown): string {
  const bytes = new TextEncoder().encode(JSON.stringify(value));
  let binary = "";
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return `v1.${btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/u, "")}`;
}

describe("parseGeneratedSubscriptionUrl", () => {
  it("loads a generated link back into the conversion form", () => {
    const token = tokenFor({
      version: 1,
      name: "个人订阅",
      nodeSettings: {
        addCountryFlag: true,
        excludePattern: "过期",
        includePattern: "US|JP",
        renameRules: [{ pattern: "USA", replacement: "US" }],
        showNodeType: true,
        skipCertVerify: false,
        sortMode: "name-asc",
        tfo: true,
        udp: true,
      },
      rulePreset: "flacier",
      sourceMode: "convert",
      sourceUserAgent: "ClashParty/2.0",
      sources: [
        { name: "订阅 1", type: "subscription", value: "https://provider.example/sub" },
        { name: "节点 1", type: "node", value: "ss://example" },
      ],
      updateIntervalHours: 12,
    });

    expect(parseGeneratedSubscriptionUrl(`https://rules.flacier.com/s/${token}/mihomo-config`))
      .toMatchObject({
        excludePattern: "过期",
        includePattern: "US|JP",
        name: "个人订阅",
        renamePattern: "USA",
        renameReplacement: "US",
        rulePreset: "flacier",
        sourceText: "https://provider.example/sub\nss://example",
        sourceUserAgent: "ClashParty/2.0",
        sortMode: "name-asc",
        target: "mihomo-config",
        updateIntervalHours: 12,
      });
  });

  it("rejects links that were not generated by this site", () => {
    expect(() => parseGeneratedSubscriptionUrl("https://example.com/sub"))
      .toThrow("不是本站生成的订阅链接");
  });
});
