const publishedRuleFiles = {
  "private-domain": "local/private-domain.list",
  "private-ip": "local/private-ip.list",
  "apple-system": "apple/system.list",
  "apple-services": "apple/services.list",
  "ai-openai": "ai/openai.list",
  "ai-anthropic": "ai/anthropic.list",
  "ai-xai": "ai/xai.list",
  "ai-google": "ai/google.list",
  "ai-coding": "ai/coding.list",
  "ai-general": "ai/general.list",
  steam: "gaming/steam.list",
  "steam-download": "gaming/steam-download.list",
  "steam-online": "gaming/steam-online.list",
  discord: "messaging/discord.list",
  developer: "developer/developer.list",
  media: "media/media.list",
  bilibili: "media/bilibili.list",
  anigamer: "media/anigamer.list",
  social: "social/social.list",
} as const;

export const mihomoRuleProviders = Object.fromEntries(
  Object.entries(publishedRuleFiles).map(([name, file]) => [
    name,
    {
      type: "http",
      behavior: "classical",
      format: "text",
      url: `https://rules.flacier.com/rules/${file}`,
      path: `./ruleset/personal/${name}.list`,
      interval: 86_400,
    },
  ]),
);

const metadataFilter = "(?i)(剩余|流量|到期|官网|客服|订阅)";

export const countryNodeFilters = {
  US: "🇺🇸|美国|美國|United States|Los Angeles|Seattle|San Jose|New York|Dallas|Chicago|(^|[ _-])(US|USA)([ _-]|$)",
  JP: "🇯🇵|日本|Japan|Tokyo|Osaka|(^|[ _-])JP([ _-]|$)",
  SG: "🇸🇬|新加坡|Singapore|(^|[ _-])SG([ _-]|$)",
  HK: "🇭🇰|香港|Hong Kong|(^|[ _-])HK([ _-]|$)",
  TW: "🇹🇼|台湾|台灣|Taiwan|Taipei|(^|[ _-])TW([ _-]|$)",
  KR: "🇰🇷|韩国|韓國|South Korea|Seoul|(^|[ _-])KR([ _-]|$)",
  GB: "🇬🇧|英国|英國|United Kingdom|London|(?:^|[ _-])(?:UK|GB)(?:[ _-]|$)",
  DE: "🇩🇪|德国|德國|Germany|Frankfurt|(?:^|[ _-])DE(?:[ _-]|$)",
  FR: "🇫🇷|法国|法國|France|Paris|(?:^|[ _-])FR(?:[ _-]|$)",
  NL: "🇳🇱|荷兰|荷蘭|Netherlands|Amsterdam|(?:^|[ _-])NL(?:[ _-]|$)",
  IT: "🇮🇹|意大利|Italy|(?:^|[ _-])IT(?:[ _-]|$)",
  ES: "🇪🇸|西班牙|Spain|(?:^|[ _-])ES(?:[ _-]|$)",
  CH: "🇨🇭|瑞士|Switzerland|(?:^|[ _-])CH(?:[ _-]|$)",
  CA: "🇨🇦|加拿大|Canada|Toronto|Vancouver|(?:^|[ _-])CA(?:[ _-]|$)",
  AU: "🇦🇺|澳大利亚|澳大利亞|Australia|Sydney|Melbourne|(?:^|[ _-])AU(?:[ _-]|$)",
  RU: "🇷🇺|俄罗斯|俄羅斯|Russia|Moscow|(?:^|[ _-])RU(?:[ _-]|$)",
  IN: "🇮🇳|印度|India|Mumbai|(?:^|[ _-])IN(?:[ _-]|$)",
  BR: "🇧🇷|巴西|Brazil|São Paulo|Sao Paulo|(?:^|[ _-])BR(?:[ _-]|$)",
  VN: "🇻🇳|越南|Vietnam|(?:^|[ _-])VN(?:[ _-]|$)",
  TH: "🇹🇭|泰国|泰國|Thailand|Bangkok|(?:^|[ _-])TH(?:[ _-]|$)",
  MY: "🇲🇾|马来西亚|馬來西亞|Malaysia|Kuala Lumpur|(?:^|[ _-])MY(?:[ _-]|$)",
  ID: "🇮🇩|印度尼西亚|印度尼西亞|Indonesia|Jakarta|(?:^|[ _-])ID(?:[ _-]|$)",
  PH: "🇵🇭|菲律宾|菲律賓|Philippines|Manila|(?:^|[ _-])PH(?:[ _-]|$)",
} as const;

export const countryFlagRules = [
  { flag: "🇺🇸", filter: countryNodeFilters.US },
  { flag: "🇯🇵", filter: countryNodeFilters.JP },
  { flag: "🇸🇬", filter: countryNodeFilters.SG },
  { flag: "🇭🇰", filter: countryNodeFilters.HK },
  { flag: "🇹🇼", filter: countryNodeFilters.TW },
  { flag: "🇰🇷", filter: countryNodeFilters.KR },
  { flag: "🇬🇧", filter: countryNodeFilters.GB },
  { flag: "🇩🇪", filter: countryNodeFilters.DE },
  { flag: "🇫🇷", filter: countryNodeFilters.FR },
  { flag: "🇳🇱", filter: countryNodeFilters.NL },
  { flag: "🇮🇹", filter: countryNodeFilters.IT },
  { flag: "🇪🇸", filter: countryNodeFilters.ES },
  { flag: "🇨🇭", filter: countryNodeFilters.CH },
  { flag: "🇨🇦", filter: countryNodeFilters.CA },
  { flag: "🇦🇺", filter: countryNodeFilters.AU },
  { flag: "🇷🇺", filter: countryNodeFilters.RU },
  { flag: "🇮🇳", filter: countryNodeFilters.IN },
  { flag: "🇧🇷", filter: countryNodeFilters.BR },
  { flag: "🇻🇳", filter: countryNodeFilters.VN },
  { flag: "🇹🇭", filter: countryNodeFilters.TH },
  { flag: "🇲🇾", filter: countryNodeFilters.MY },
  { flag: "🇮🇩", filter: countryNodeFilters.ID },
  { flag: "🇵🇭", filter: countryNodeFilters.PH },
] as const;

function countryGroup(name: string, filter: string) {
  return {
    name,
    type: "select",
    "include-all": true,
    "empty-fallback": "DIRECT",
    "exclude-type": "direct",
    filter,
    "exclude-filter": metadataFilter,
  };
}

export const mihomoProxyGroups = [
  {
    name: "AUTO",
    type: "url-test",
    "include-all": true,
    "exclude-type": "direct",
    url: "https://cp.cloudflare.com/generate_204",
    interval: 300,
    tolerance: 80,
    "exclude-filter": metadataFilter,
  },
  countryGroup(
    "US",
    `(?i)(${countryNodeFilters.US})`,
  ),
  countryGroup(
    "JP",
    `(?i)(${countryNodeFilters.JP})`,
  ),
  countryGroup(
    "SG",
    `(?i)(${countryNodeFilters.SG})`,
  ),
  countryGroup(
    "HK",
    `(?i)(${countryNodeFilters.HK})`,
  ),
  countryGroup(
    "TW",
    `(?i)(${countryNodeFilters.TW})`,
  ),
  countryGroup(
    "KR",
    `(?i)(${countryNodeFilters.KR})`,
  ),
  countryGroup(
    "EU",
    "(?i)(🇬🇧|🇩🇪|🇫🇷|🇳🇱|🇮🇹|🇪🇸|🇨🇭|🇪🇺|英国|英國|United Kingdom|London|德国|德國|Germany|Frankfurt|法国|法國|France|Paris|荷兰|荷蘭|Netherlands|Amsterdam|意大利|Italy|西班牙|Spain|瑞士|Switzerland|(^|[ _-])(UK|GB|DE|FR|NL|IT|ES|CH|EU)([ _-]|$))",
  ),
  {
    name: "GLOBAL",
    type: "select",
    proxies: ["AUTO", "US", "JP", "SG", "HK", "TW", "KR", "EU", "DIRECT"],
    "include-all": true,
    "exclude-filter": metadataFilter,
  },
  { name: "AI", type: "select", proxies: ["GLOBAL", "US", "JP", "SG", "TW"] },
  { name: "APPLE", type: "select", proxies: ["DIRECT", "GLOBAL", "US", "JP", "SG"] },
  { name: "STEAM", type: "select", proxies: ["DIRECT", "GLOBAL", "JP", "US", "SG"] },
  {
    name: "STEAM-DOWNLOAD",
    type: "select",
    proxies: ["DIRECT", "GLOBAL", "JP", "US", "SG", "HK", "TW"],
  },
  {
    name: "STEAM-ONLINE",
    type: "select",
    proxies: ["DIRECT", "GLOBAL", "JP", "US", "SG", "HK", "TW"],
  },
  { name: "DISCORD", type: "select", proxies: ["GLOBAL", "US", "JP", "SG", "DIRECT"] },
  { name: "DEV", type: "select", proxies: ["GLOBAL", "DIRECT", "US", "JP", "SG"] },
  { name: "MEDIA", type: "select", proxies: ["GLOBAL", "US", "JP", "SG", "DIRECT"] },
  { name: "BILIBILI", type: "select", proxies: ["DIRECT", "GLOBAL", "HK", "TW", "SG"] },
  { name: "ANIGAMER", type: "select", proxies: ["TW", "GLOBAL", "DIRECT", "AUTO"] },
  { name: "SOCIAL", type: "select", proxies: ["GLOBAL", "US", "JP", "SG", "DIRECT"] },
  { name: "DEFAULT", type: "select", proxies: ["GLOBAL", "DIRECT", "AUTO"] },
] as const;

export const mihomoRules = [
  "RULE-SET,private-domain,DIRECT",
  "RULE-SET,private-ip,DIRECT,no-resolve",
  "RULE-SET,apple-system,DIRECT",
  "RULE-SET,apple-services,APPLE",
  "PROCESS-NAME-REGEX,(?i)^codex(\\.exe)?$,AI",
  "PROCESS-NAME-REGEX,(?i)^claude(\\.exe)?$,AI",
  "RULE-SET,ai-openai,AI",
  "RULE-SET,ai-anthropic,AI",
  "RULE-SET,ai-xai,AI",
  "RULE-SET,ai-google,AI",
  "RULE-SET,ai-coding,AI",
  "RULE-SET,ai-general,AI",
  "RULE-SET,steam-download,STEAM-DOWNLOAD",
  "RULE-SET,steam-online,STEAM-ONLINE",
  "RULE-SET,steam,STEAM",
  "RULE-SET,discord,DISCORD",
  "RULE-SET,developer,DEV",
  "RULE-SET,bilibili,BILIBILI",
  "RULE-SET,anigamer,ANIGAMER",
  "RULE-SET,media,MEDIA",
  "RULE-SET,social,SOCIAL",
  "MATCH,DEFAULT",
] as const;
